### ISSUE TITLE
DVA 怎么支持react-navigation的subscriptions？

### ISSUE THREAD

**Issue by kala888** [nihgwu/react-native-dva-starter#11]
不是个bug，就是求大神帮忙接解决一个问题，查了半天了
例如我想订阅一个页面被调用

**Comment by nihgwu** [comment]
https://reactnavigation.org/docs/guides/screen-tracking#Screen-tracking

**Comment by kala888** [comment]
好像不太一样，不过我已经找到方法了。
1、在models/router.js里面获取当前页面，然后发送事件
```
    const payload = yield take(actions)
                    const routerState = yield select(state => state.router)
                    const navigateInfo = routerReducer(routerState, payload)
                    const currentScreen = getCurrentScreen(navigateInfo)
                    console.log("currentScreen",currentScreen)
                    yield put({
                        type: 'apply',
                        payload:{
                            ...navigateInfo,
                            currentScreen
                        },
                    })
                    event.emit('ScreenChanged',currentScreen)
```
2、在其他的model里面就可以通过subscriptions订阅页面变化了（注册事件）
```
 subscriptions: {
        setup ({dispatch}) {
            event.on('ScreenChanged', (screenName) => {
                if (screenName === 'EditProfile') {
                    dispatch(createAction('loadProfile')())
                }
            })
        },
    },
```

**Comment by nihgwu** [comment]
nice approach, actually there are several ways to achieve that
1. simply define a `watcher` to `take` navigate actions
2. use `EventEmitter` as you did
3. `onNavigationStateChange` and etc

**Comment by kala888** [comment]
I not very clear how to initial data when a screen open. eg, when the app load, the customer could see button named "Me" on the footer, and then he click the button, the screen changed, what's best practice of load the data from service and then render the UI? could you add this case to this starter?
