### ISSUE TITLE
How to change the route in the models？

### ISSUE THREAD

**Issue by tmachr** [nihgwu/react-native-dva-starter#12]
Just like what you wrote in app.js，Login successfully, jump to the home page，But I have no use for this method。

**Comment by nihgwu** [comment]
not quick clear what's you question

**Comment by kala888** [comment]
@tmachr，try to explain with your native language.
Is this what you want?
![image](https://user-images.githubusercontent.com/1215976/28074320-d8505066-668a-11e7-890e-803eb47c4cbe.png)
