### ISSUE TITLE
react-navigation SET_PARAMS参数不能传递方法

### ISSUE THREAD

**Issue by Nokecy** [nihgwu/react-native-dva-starter#14]
现在需要在导航栏右侧加一个按钮。
`_onDrawerOpenHide() {
    this._drawer.Open();
  }`

`componentDidMount() {
    this.props.navigation.setParams({ navigatePress: this._onDrawerOpenHide })
  }`
用这种方式获取不了
`navigation.state.params.navigatePress()`

请问有什么好的解决方案吗？

**Comment by nihgwu** [comment]
irrelevant with this repo, I think you should control the drawer via state

**Comment by kala888** [comment]
今天我也整了这个半天，不是dva的问题，是react-navigation的用法或者问题. 请关注
https://github.com/RabbitDream/ReactNavigationDemo/issues/1

**Comment by kala888** [comment]
Same issue, but different implement, here is the code.
I find that, i can set navigation parameters when the screen in the footer tab(Account.js)
but the very similar code in Details.js, not works fine, could not set params.

https://github.com/kala888/react-native-dva-starter/commit/64481d5d3d65ef03240b0f14ffdc066ab09fc874

**Comment by Nokecy** [comment]
@kala888  see models/route.js [https://github.com/nihgwu/react-native-dva-starter/blob/master/app/models/router.js#L34-L36](url)
