### ISSUE TITLE
dva和react-native需求的react版本不一致

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [nihgwu/react-native-dva-starter#16]
"dva": "1.3.0-beta.4",
 "react": "16.0.0-alpha.12",
这个版本的dva要求的是15.X的版本，这样会导致安装不了

**Comment by nihgwu** [comment]
不过是个警告，不会导致安装不了，还有这个是dva的peerDependencies造成的

**Comment by liuhuapiaoyuan** [comment]
嗯 是的。。
