### ISSUE TITLE
undefined is not an object (evaluating _ref.routes)

### ISSUE THREAD

**Issue by hu272293309** [nihgwu/react-native-dva-starter#17]
react-native run-ios 
undefined is not an object (evaluating _ref.routes)
![image](https://user-images.githubusercontent.com/938996/29313819-25192566-81ee-11e7-9c7a-0925e75da1d9.png)

**Comment by zuoge85** [comment]
我也遇到了，毫无头绪。。

**Comment by zuoge85** [comment]
已经解决饶了好几个弯，最后找到了关键

去掉index.js 的 persistStore 

> 原因大概是因为你的导航器定义改变了，但是存储的是过时的内容
😝

**Comment by nihgwu** [comment]
@zuoge85 thanks for your solution

**Comment by nihgwu** [comment]
fixed in https://github.com/nihgwu/react-native-dva-starter/commit/42253ae3970cbe02cecb4f63af2126e76acc38f8
