### ISSUE TITLE
如何在store中加入redux-persist

### ISSUE THREAD

**Issue by bestlbw** [nihgwu/react-native-dva-starter#2]
我在createDva.js中修改了 ，但是不起效
![image](https://cloud.githubusercontent.com/assets/23213008/25038864/66b11eb4-2133-11e7-917a-2f34a4678971.png)
如能帮助 不胜感激， 
还有一个问题 如果我有多个tabnavigator  该怎么和redux进行关联

**Comment by nihgwu** [comment]
https://github.com/nihgwu/react-native-dva-starter/commit/8b2012178ea77e54a8ea6aebb8c6386e1ffbda0b

**Comment by bestlbw** [comment]
我在一个界面中使用了tabrouter
![image](https://cloud.githubusercontent.com/assets/23213008/25086738/838caf38-239c-11e7-895f-24dea7ebffff.png)
怎么将他使用redux 管理呢 看log 只有dispatch，请帮助下
