### ISSUE TITLE
例子运行起来了，怎样在首页前再加一个页面

### ISSUE THREAD

**Issue by yzj450** [nihgwu/react-native-dva-starter#23]
例子运行起来了，怎样在首页前再加一个页面，我想加一个登陆页面然后点击跳转再加载到主页面，工程中怎样添加一个页面？dva的实现还不是太明白，烦请回复，谢谢。

**Comment by nihgwu** [comment]
看 router.js 的定义

**Comment by yzj450** [comment]
感谢回复，我将附件中红框的代码调换了位置，Login页面只闪现了一下就自己跳到home页了，我想知道在route.js中怎么添加一个页面在home页前面，Login不要是react-navigation的中页面，单独的页面，感谢回复，万分谢谢。
const AppNavigator = StackNavigator(
  {
    //Login: { screen: Login },
    //Main: { screen: MainNavigator },
Login: { screen: Login },
Main: { screen: MainNavigator },
  },



在 2017-09-12 18:05:01，"Neo" <notifications@github.com> 写道：


Closed #23.
