### ISSUE TITLE
在route.js中怎么添加一个页面在home页前面

### ISSUE THREAD

**Issue by yzj450** [nihgwu/react-native-dva-starter#24]
感谢回复，我将附件中红框的代码调换了位置，Login页面只闪现了一下就自己跳到home页了，我想知道在route.js中怎么添加一个页面在home页前面，Login不要是react-navigation的中页面，单独的页面，感谢回复，万分谢谢。
const AppNavigator = StackNavigator(
  {
    //Login: { screen: Login },
    //Main: { screen: MainNavigator },
Login: { screen: Login },
Main: { screen: MainNavigator },
  },

**Comment by nihgwu** [comment]
闪现就跳应该是因为 redux-persist 造成的，你可以注释掉那段代码再试，还有这种问题应该去看 react-navigation 而不是在这提问
