### ISSUE TITLE
能否实现动态加载model和routes？

### ISSUE THREAD

**Issue by LarchLiu** [nihgwu/react-native-dva-starter#27]
请问 RN + dva-core + react-navigation 的组合能否像 react + dva 那样实现动态加载model和routes？
如何实现？

**Comment by nihgwu** [comment]
动态路由主要是为了 code splitting, 感觉在 RN 里并没有必要，不过 react-navigation 提供了 `getScreen` 方法，应该是能做到动态加载 model 跟 routes 的
