### ISSUE TITLE
我直接clone下代码，然后npm install，出错，请问如何解决

### ISSUE THREAD

**Issue by jove9834** [nihgwu/react-native-dva-starter#3]
你好，以下是出错的信息，谢谢！
npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@16.0.0-alpha.6 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer dva@1.3.0-beta.3 wants react@15.x
npm ERR! peerinvalid Peer react-native@0.43.3 wants react@16.0.0-alpha.6
npm ERR! peerinvalid Peer react-navigation@1.0.0-beta.7 wants react@*
npm ERR! peerinvalid Peer react-test-renderer@15.4.2 wants react@^15.4.2

**Comment by nihgwu** [comment]
They are all peerDependencies warnings, you can ignore them
