### ISSUE TITLE
Why you removed redux-persist ?

### ISSUE THREAD

**Issue by Kottidev** [nihgwu/react-native-dva-starter#32]
redux-persist v5 support new use cases :

* code splitting reducers
* easier to ship persist support inside of other libs (e.g. redux-offline)
* ability to colocate persistence rules with the reducer it pertains to
* first class migration support
* enable PersistGate react component which blocks rendering until persistence is complete (and enables similar patterns for integration)
* possible to nest persistence
* gaurantee consistent state atoms
* better debugability and extensibility

**Comment by nihgwu** [comment]
I don't use `redux-persist` in my own projects, I added it just to demo how to integrate it with dva, I upgraded the dependencies several days ago and find it changed its api completely and I didn't have time to migrate so I just removed it
