### ISSUE TITLE
TypeError:undefined is not a function(near '...addListener...')

### ISSUE THREAD

**Issue by HankinsPan** [nihgwu/react-native-dva-starter#36]
![simulator screen shot - iphone 6 - 2018-02-11 at 17 15 16](https://user-images.githubusercontent.com/16145351/36071786-2b8b1b72-0f4f-11e8-9960-8455d3f7cdb4.png)

When I clone the project and use npm install, it show me this error.

**Comment by nihgwu** [comment]
resolved after upgraded to the latest packages
