### ISSUE TITLE
给react-native-dva-starter写了个cli工具

### ISSUE THREAD

**Issue by xuan45** [nihgwu/react-native-dva-starter#40]
cli工具在[https://github.com/danmin25/dva-native-cli](https://github.com/danmin25/dva-native-cli)，后续会持续更新和改进，另外container目录里面的loading组件是不是作为组件放在components目录里面更为合适？

**Comment by nihgwu** [comment]
`Loading` 本来就是个页面，初始化时候显示的

话说其实 react-native-cli 本身是支持 template 的，稍微改下代码组织方式即可
还有我觉得 template 目录是不是可以直接用 git rpo，不然每次还得同步

**Comment by danmin25** [comment]
git clone完全OK的，另外是不是可以考虑下可配置项目名称？

**Comment by nihgwu** [comment]
什么意思？

**Comment by danmin25** [comment]
就是项目名称，模板是DvaStarter，其实也无关紧要，不知道有没有这个必要

**Comment by nihgwu** [comment]
这个 https://github.com/junedomingo/react-native-rename ?

**Comment by danmin25** [comment]
效果一样，就是速度有点慢，不知道使用者能不能接受

**Comment by danmin25** [comment]
现在cli支持直接git仓库或者创建模板，还有自动rename功能
还有app需不需要增加一个启动页面和封装fetch？如果有需要的话我可以pr，正在写

**Comment by nihgwu** [comment]
👍，fetch的话我一直想想写一个例子的，就是不知道哪什么api合适

**Comment by danmin25** [comment]
可以自己用node搭，或者网上有很多免费的api，我想了想启动页配置比较灵活，还是不要集成进去了。可以写个例子

**Comment by nihgwu** [comment]
自己搭倒是没必要，我牛读里用的都是现成的api，但是都不太通用，主要是我可以把我自用的 request 还有其他一下utils都放进来，还有分页处理

**Comment by nihgwu** [comment]
看了下感觉 reddit 的好像还好，就用这个吧

**Comment by danmin25** [comment]
可以，另外cli工具已经稳定，大家可以使用了

**Comment by nihgwu** [comment]
嗯，我到时候加到readme里去 👍

**Comment by nihgwu** [comment]
@xuan45 方便提个PR加到Readme里面吗

**Comment by xuan45** [comment]
@nihgwu 可以的

**Comment by nihgwu** [comment]
thanks
