### ISSUE TITLE
windows 10下添加react-navigation 报错

### ISSUE THREAD

**Issue by vince-fly** [nihgwu/react-native-dva-starter#41]
Yarn version: 
  1.5.1

Node version: 
  8.9.1

Platform: 
  win32 x64

[2/4] Fetching packages...
error An unexpected error occurred: "https://codeload.github.com/react-navigation/react-native-tab-view/tar.gz/36ebd834d78b841fc19778c966465d02fd1213bb: connect ETIMEDOUT 54.251.140.56:443".

**Comment by vince-fly** [comment]
无论使用npm，还是yarn，都报错。。。怎么破？急等。。。

**Comment by nihgwu** [comment]
irrelevant with this repo
