### ISSUE TITLE
如何用expo和Genymotion预览应用

### ISSUE THREAD

**Issue by DrakeXiang** [nihgwu/react-native-dva-starter#43]
直接`run-android`报错`FAILURE: Build failed with an exception.`。而用Expo XDE也不行，说`Missing app.json`，往里面加入对应expo信息后又报`Cannot find module 'D:\Coding\work\...\node_modules\expo\tools\LogReporter'`。然后就卡在这里了。

如何才能用expo预览应用，或者还有其他什么方式能方便开发时预览？

**Comment by nihgwu** [comment]
没用过 expo，不过用 expo 的话需要修改代码的吧
`run-android` 你在其他 RN 项目可以跑吗？不过我貌似好久没跑这个命令了，之前一直有测试 Android 版的

**Comment by DrakeXiang** [comment]
@nihgwu 新接触rn，之前打算用dva搭框架，然而卡在这里搭不起来就改用官方的crna了。。

**Comment by lzfxxx** [comment]
@DrakeXiang 请问后来又成功用react-native-dva-starter 和 expo吗，还是用create-react-native-app了？

**Comment by DrakeXiang** [comment]
@lzfxxx 最后用的create-react-native-app
