### ISSUE TITLE
plz update react-navigation to Version 2.0.1

### ISSUE THREAD

**Issue by flasco** [nihgwu/react-native-dva-starter#46]
now the react-navigation latest version is 2.0.1, can you update example? thanks!

**Comment by YinRenjie1993** [comment]
+1

**Comment by flasco** [comment]
I solve this problem, the first time I upgrade to version 2.0.1 I faced the problem was `context._currentValue = currentValue`, it due to your react version, latest react-navigation use context API, so the react-native version must > `0.55.1`, the config is very similar to example, just change a little.

v2 react-navigation solve many problem, hope you can use it, enjoy~

**Comment by nihgwu** [comment]
can you send a PR? thanks

**Comment by flasco** [comment]
I will try to send a PR if I have time tomorrow, now is too late :)
