### ISSUE TITLE
dvanative new start ----command not found: dvanative

### ISSUE THREAD

**Issue by xuxichen** [nihgwu/react-native-dva-starter#51]
大佬，我按照readme里初始化项目，爆找不到dvanative 命令
![631527055843_ pic](https://user-images.githubusercontent.com/18108140/40407097-dabec86a-5e95-11e8-8569-08863cdf3b9c.jpg)

**Comment by flasco** [comment]
-g全局安装了？

**Comment by zhou-ting** [comment]
我也是啊。大佬
![snip20180523_1](https://user-images.githubusercontent.com/22723026/40411133-1ea505ce-5ea2-11e8-89b4-351f7cb5e62b.png)

**Comment by xuxichen** [comment]
@flasco 是装在根目录了的

**Comment by xuan45** [comment]
@xuxichen @flasco @zhou-ting 我不太清楚你们那边的问题，但是我通过-g安装后可以正常创建项目并启动，我看你们安装的版本怎么和我的不一样？现在是0.0.8版本，命令由dva-native变成了dvanative，你们可以尝试安装0.0.8版本的

**Comment by for4die** [comment]
是npm淘宝源的问题，切换成官方源就可以下载到最新0.0.8版本
切换方法：（nrm切换）
npm install -g nrm 
nrm ls

* npm ---- https://registry.npmjs.org/
  cnpm --- http://r.cnpmjs.org/
  taobao - https://registry.npm.taobao.org/
  nj ----- https://registry.nodejitsu.com/
  rednpm - http://registry.mirror.cqupt.edu.cn/
  npmMirror  https://skimdb.npmjs.com/registry/
  edunpm - http://registry.enpmjs.org/

nrm use npm

**Comment by nihgwu** [comment]
thanks for all

**Comment by nihgwu** [comment]
BTW, I synced the version on taobao's registry manually
