### ISSUE TITLE
升级后了好像会报错

### ISSUE THREAD

**Issue by YinRenjie1993** [nihgwu/react-native-dva-starter#52]
点登录，在登录就会报错了

**Comment by flasco** [comment]
因为点击login会执行一句Navigations.reset ，而这一句在v2的版本已经过期了，具体你可以看一下源码上的注释，替代的方法的话你可以使用navigate直接跳回首页，因为现在v2的navigate会优先跳转到栈中已经有的item（作为替代方法的stackAction.reset目前有点看不懂，所以先用navigate吧）

**Comment by nihgwu** [comment]
fixed in https://github.com/nihgwu/react-native-dva-starter/commit/0bca3c32b3800c6613e0756b68adf170b8161354
