### ISSUE TITLE
Take DrawerNavigator as the root navigator, not the stackNavigator

### ISSUE THREAD

**Issue by wanglei1348** [nihgwu/react-native-dva-starter#55]
hi:
 i found one wired thing here, when i take DrawerNavigator as the root navigator, not the stackNavigator, the drawerNavigator will does not work as it expected!
 the issue is when i click one of the drawer item, thing happened, not go to the corresponding page maped to the drawerNavigator!
 is somethign i missed or ?

**Comment by nihgwu** [comment]
sorry it seems to be not related to this starter itself
