### ISSUE TITLE
navigation.getChildNavigation is not a function

### ISSUE THREAD

**Issue by tiyunchen** [nihgwu/react-native-dva-starter#56]
https://stackoverflow.com/questions/50813011/navigation-getchildnavigation-is-not-a-function/50813248?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by zhuanglong** [comment]
+1

**Comment by alex86w** [comment]
+1

**Comment by dreamHeroK** [comment]
i have a same problem @nihgwu

**Comment by nihgwu** [comment]
fixed in https://github.com/nihgwu/react-native-dva-starter/commit/0bca3c32b3800c6613e0756b68adf170b8161354
