### ISSUE TITLE
打开同一个页面问题

### ISSUE THREAD

**Issue by janpo** [nihgwu/react-native-dva-starter#57]
1. 运行DEMO
2. 点Goto Detail
3. 再继续点Goto Detail 不再会有页面切换动画，好像一直在替换当前页面

**Comment by flasco** [comment]
因为现在（v2）react-navigation的navigate跳转策略已经改变了，相同路由名不会再次push，而是寻找栈中已有的item。

**Comment by janpo** [comment]
@flasco thx
