### ISSUE TITLE
react-navigation官方不建议用redux，怎么让react-navigation不用redux，但是其他组件都用呢？

### ISSUE THREAD

**Issue by bjwulin** [nihgwu/react-native-dva-starter#60]
我看官方很反对用redux，以后也不支持和redux的整合，我们能不能组件里面用redux，但是react-navigation不用？

还有一个问题，一直想不明白，比如我第一次navigate ScreenA，检索数据，然后数据存在redux store，中，当我第二次navigate ScreenA时，由于数据还在store里面，那么首先给用户看到的是上次的数据，然后检索后台数据回来才更新，这样给用户的体验感很不好！我想是不是在ScreenA做一个firstLoading的状态，只要是新打开的，我都根据这个状态显示等待提示？

**Comment by nihgwu** [comment]
关于第一个，完全没问题，至于第二个，如果你每次进入这个页面都重新刷新数据，那么你根本没有把数据存到store的必要，还不如直接写在组件本身的state里面
