### ISSUE TITLE
按步骤安装，但是报错：dvanative: command not found

### ISSUE THREAD

**Issue by rockvic** [nihgwu/react-native-dva-starter#61]
操作环境为MacOS 10，按照步骤安装的，但是报错找不到dvanative命令。请问是什么原因呢？
<img width="551" alt="dvanative" src="https://user-images.githubusercontent.com/3436251/42216218-a93d450e-7ef3-11e8-89aa-7502bf8991fa.png">

**Comment by nihgwu** [comment]
would #51 be helpful?
