### ISSUE TITLE
怎么获取router信息

### ISSUE THREAD

**Issue by gao520sun** [nihgwu/react-native-dva-starter#62]
...
const App = reduxifyNavigator(AppNavigator, 'root')
 return <App dispatch={dispatch} state={router} />
我在Detail详情页面怎么获取 router全部信息？
除了@connect(({router }) => ({router }))用这个
 'this.props.......', { screenProps: undefined,
  navigation: 
   { goBack: [Function],
     navigate: [Function],
     setParams: [Function],
     pop: [Function],
     popToTop: [Function],
     push: [Function],
     replace: [Function],
     reset: [Function],
     dismiss: [Function],
     state: 
      { params: undefined,
        routeName: 'Detail',
        key: 'id-1531808984051-2' },
     router: undefined,
     actions: 
      { goBack: [Function: goBack],
        navigate: [Function: navigate],
        setParams: [Function: setParams],
        pop: [Function: pop],
        popToTop: [Function: popToTop],
        push: [Function: push],
        replace: [Function: replace],
        reset: [Function: reset],
        dismiss: [Function: dismiss] },
     getParam: [Function],
     getChildNavigation: [Function: getChildNavigation],
     isFocused: [Function: isFocused],
     dispatch: [Function],
     getScreenProps: [Function: getScreenProps],
     dangerouslyGetParent: [Function],
     addListener: [Function: addListener] },
  dispatch: [Function] }

**Comment by nihgwu** [comment]
connect router
