### ISSUE TITLE
undefined is not an object(evaluating '_ref.routes')

### ISSUE THREAD

**Issue by hyhajnal** [nihgwu/react-native-dva-starter#7]
在新添一个tab后就报错，不知为何，google没搜到这个问题，
只在react-navigation看到这个issue[1408](https://github.com/react-community/react-navigation/issues/1408)
但还是不知道怎么解决，求助～
``` js
const HomeNavigator = TabNavigator(
  {
    Home: { screen: Home },
    Account: { screen: Account },
    Msg: { screen: Msg}, //新添一个tab
  },
  {
    tabBarComponent: TabBarBottom,
    tabBarPosition: 'bottom',
    swipeEnabled: false,
    animationEnabled: false,
    lazyLoad: true,
  },
)
```
<img src="https://cloud.githubusercontent.com/assets/15121143/26274354/a8b244f6-3d7a-11e7-8f16-a1e6dc5b16f3.png" width="50%" height="50%" />

**Comment by nihgwu** [comment]
I can't reproduce it, perhaps there is something wrong with your `Msg` component

**Comment by hyhajnal** [comment]
I git clone the project, haven't  changed files yet, except added a Msg component ( PS: Msg component just a copy of Account component, and rename it ). 
Then the error occurred.
and when i del the Msg component, recover it to the begin , rebuild,  the error still exist
do you think is this the reason for version of react-navigation ?

**Comment by vance-liu** [comment]
+1 , same error, I just change TabNavigator options.

```
const HomeNavigator = TabNavigator(
  {
    Home: { screen: Home },
    Account: { screen: Account },
    Account2: { screen: Account },
  },
  {
    tabBarComponent: TabBarBottom,
    tabBarPosition: 'bottom',
    swipeEnabled: false,
    animationEnabled: false,
    lazyLoad: true,
  }
)
```

**Comment by vance-liu** [comment]
重新编译再次试了下，感觉是dva热加载的问题，不知道有没有解决方案

**Comment by vance-liu** [comment]
@nihgwu

**Comment by nihgwu** [comment]
@vance-liu I don't think so, and I don't know how to fix it, I can't reproduce it, seems someone using react-navigation also be bothered by this problem, I don't think it's a issue from dva
