### ISSUE TITLE
ExceptionsManager.js:63 Cannot read property 'routes' of undefined

### ISSUE THREAD

**Issue by eynil** [nihgwu/react-native-dva-starter#8]
git clone and npm install repo ,  react-native run-ios report as follows 'ExceptionsManager.js:63 Cannot read property 'routes' of undefined'

**Comment by nihgwu** [comment]
can't reproduce it, need more information

**Comment by eynil** [comment]
in ios the error likes : [http://zeiagu.oss-cn-shanghai.aliyuncs.com/issues/rcd-ios.gif](url)


but it works in android [http://zeiagu.oss-cn-shanghai.aliyuncs.com/issues/rcd-android.gif](url)

and the console : [http://zeiagu.oss-cn-shanghai.aliyuncs.com/issues/rcd-console2.gif](url)

**Comment by eynil** [comment]
看了react-navigator项目中[Contributors Guide](https://github.com/react-community/react-navigation/blob/master/docs/guides/Contributors.md#development) 后，把系统从10.11升级到10.12.5后，问题解决了； @nihgwu

**Comment by nihgwu** [comment]
Interesting solution 😄

**Comment by zuoge85** [comment]
@eynil 我全部升级到最新都不行

**Comment by zuoge85** [comment]
已经解决 #17
